# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/margot/Downloads/clion-2019.3.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/margot/Downloads/clion-2019.3.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/margot/NFS-Next-Gen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/margot/NFS-Next-Gen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/margot/Downloads/clion-2019.3.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/margot/Downloads/clion-2019.3.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/margot/NFS-Next-Gen/CMakeFiles /home/margot/NFS-Next-Gen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/margot/NFS-Next-Gen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NFS_Next_Gen

# Build rule for target.
NFS_Next_Gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NFS_Next_Gen
.PHONY : NFS_Next_Gen

# fast build rule for target.
NFS_Next_Gen/fast:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/build
.PHONY : NFS_Next_Gen/fast

src/graphics/graphicFunc.o: src/graphics/graphicFunc.cpp.o

.PHONY : src/graphics/graphicFunc.o

# target to build an object file
src/graphics/graphicFunc.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/graphicFunc.cpp.o
.PHONY : src/graphics/graphicFunc.cpp.o

src/graphics/graphicFunc.i: src/graphics/graphicFunc.cpp.i

.PHONY : src/graphics/graphicFunc.i

# target to preprocess a source file
src/graphics/graphicFunc.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/graphicFunc.cpp.i
.PHONY : src/graphics/graphicFunc.cpp.i

src/graphics/graphicFunc.s: src/graphics/graphicFunc.cpp.s

.PHONY : src/graphics/graphicFunc.s

# target to generate assembly for a file
src/graphics/graphicFunc.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/graphicFunc.cpp.s
.PHONY : src/graphics/graphicFunc.cpp.s

src/graphics/login.o: src/graphics/login.cpp.o

.PHONY : src/graphics/login.o

# target to build an object file
src/graphics/login.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/login.cpp.o
.PHONY : src/graphics/login.cpp.o

src/graphics/login.i: src/graphics/login.cpp.i

.PHONY : src/graphics/login.i

# target to preprocess a source file
src/graphics/login.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/login.cpp.i
.PHONY : src/graphics/login.cpp.i

src/graphics/login.s: src/graphics/login.cpp.s

.PHONY : src/graphics/login.s

# target to generate assembly for a file
src/graphics/login.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/login.cpp.s
.PHONY : src/graphics/login.cpp.s

src/graphics/menu.o: src/graphics/menu.cpp.o

.PHONY : src/graphics/menu.o

# target to build an object file
src/graphics/menu.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/menu.cpp.o
.PHONY : src/graphics/menu.cpp.o

src/graphics/menu.i: src/graphics/menu.cpp.i

.PHONY : src/graphics/menu.i

# target to preprocess a source file
src/graphics/menu.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/menu.cpp.i
.PHONY : src/graphics/menu.cpp.i

src/graphics/menu.s: src/graphics/menu.cpp.s

.PHONY : src/graphics/menu.s

# target to generate assembly for a file
src/graphics/menu.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/menu.cpp.s
.PHONY : src/graphics/menu.cpp.s

src/graphics/pauseInTheGame.o: src/graphics/pauseInTheGame.cpp.o

.PHONY : src/graphics/pauseInTheGame.o

# target to build an object file
src/graphics/pauseInTheGame.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/pauseInTheGame.cpp.o
.PHONY : src/graphics/pauseInTheGame.cpp.o

src/graphics/pauseInTheGame.i: src/graphics/pauseInTheGame.cpp.i

.PHONY : src/graphics/pauseInTheGame.i

# target to preprocess a source file
src/graphics/pauseInTheGame.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/pauseInTheGame.cpp.i
.PHONY : src/graphics/pauseInTheGame.cpp.i

src/graphics/pauseInTheGame.s: src/graphics/pauseInTheGame.cpp.s

.PHONY : src/graphics/pauseInTheGame.s

# target to generate assembly for a file
src/graphics/pauseInTheGame.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/pauseInTheGame.cpp.s
.PHONY : src/graphics/pauseInTheGame.cpp.s

src/graphics/scoreTable.o: src/graphics/scoreTable.cpp.o

.PHONY : src/graphics/scoreTable.o

# target to build an object file
src/graphics/scoreTable.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/scoreTable.cpp.o
.PHONY : src/graphics/scoreTable.cpp.o

src/graphics/scoreTable.i: src/graphics/scoreTable.cpp.i

.PHONY : src/graphics/scoreTable.i

# target to preprocess a source file
src/graphics/scoreTable.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/scoreTable.cpp.i
.PHONY : src/graphics/scoreTable.cpp.i

src/graphics/scoreTable.s: src/graphics/scoreTable.cpp.s

.PHONY : src/graphics/scoreTable.s

# target to generate assembly for a file
src/graphics/scoreTable.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/scoreTable.cpp.s
.PHONY : src/graphics/scoreTable.cpp.s

src/graphics/wrapFunc.o: src/graphics/wrapFunc.cpp.o

.PHONY : src/graphics/wrapFunc.o

# target to build an object file
src/graphics/wrapFunc.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/wrapFunc.cpp.o
.PHONY : src/graphics/wrapFunc.cpp.o

src/graphics/wrapFunc.i: src/graphics/wrapFunc.cpp.i

.PHONY : src/graphics/wrapFunc.i

# target to preprocess a source file
src/graphics/wrapFunc.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/wrapFunc.cpp.i
.PHONY : src/graphics/wrapFunc.cpp.i

src/graphics/wrapFunc.s: src/graphics/wrapFunc.cpp.s

.PHONY : src/graphics/wrapFunc.s

# target to generate assembly for a file
src/graphics/wrapFunc.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/graphics/wrapFunc.cpp.s
.PHONY : src/graphics/wrapFunc.cpp.s

src/logic/ClientState.o: src/logic/ClientState.cpp.o

.PHONY : src/logic/ClientState.o

# target to build an object file
src/logic/ClientState.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/ClientState.cpp.o
.PHONY : src/logic/ClientState.cpp.o

src/logic/ClientState.i: src/logic/ClientState.cpp.i

.PHONY : src/logic/ClientState.i

# target to preprocess a source file
src/logic/ClientState.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/ClientState.cpp.i
.PHONY : src/logic/ClientState.cpp.i

src/logic/ClientState.s: src/logic/ClientState.cpp.s

.PHONY : src/logic/ClientState.s

# target to generate assembly for a file
src/logic/ClientState.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/ClientState.cpp.s
.PHONY : src/logic/ClientState.cpp.s

src/logic/Game.o: src/logic/Game.cpp.o

.PHONY : src/logic/Game.o

# target to build an object file
src/logic/Game.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/Game.cpp.o
.PHONY : src/logic/Game.cpp.o

src/logic/Game.i: src/logic/Game.cpp.i

.PHONY : src/logic/Game.i

# target to preprocess a source file
src/logic/Game.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/Game.cpp.i
.PHONY : src/logic/Game.cpp.i

src/logic/Game.s: src/logic/Game.cpp.s

.PHONY : src/logic/Game.s

# target to generate assembly for a file
src/logic/Game.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/Game.cpp.s
.PHONY : src/logic/Game.cpp.s

src/logic/GameState.o: src/logic/GameState.cpp.o

.PHONY : src/logic/GameState.o

# target to build an object file
src/logic/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/GameState.cpp.o
.PHONY : src/logic/GameState.cpp.o

src/logic/GameState.i: src/logic/GameState.cpp.i

.PHONY : src/logic/GameState.i

# target to preprocess a source file
src/logic/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/GameState.cpp.i
.PHONY : src/logic/GameState.cpp.i

src/logic/GameState.s: src/logic/GameState.cpp.s

.PHONY : src/logic/GameState.s

# target to generate assembly for a file
src/logic/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/GameState.cpp.s
.PHONY : src/logic/GameState.cpp.s

src/logic/MapGenerator.o: src/logic/MapGenerator.cpp.o

.PHONY : src/logic/MapGenerator.o

# target to build an object file
src/logic/MapGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/MapGenerator.cpp.o
.PHONY : src/logic/MapGenerator.cpp.o

src/logic/MapGenerator.i: src/logic/MapGenerator.cpp.i

.PHONY : src/logic/MapGenerator.i

# target to preprocess a source file
src/logic/MapGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/MapGenerator.cpp.i
.PHONY : src/logic/MapGenerator.cpp.i

src/logic/MapGenerator.s: src/logic/MapGenerator.cpp.s

.PHONY : src/logic/MapGenerator.s

# target to generate assembly for a file
src/logic/MapGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/MapGenerator.cpp.s
.PHONY : src/logic/MapGenerator.cpp.s

src/logic/ServerState.o: src/logic/ServerState.cpp.o

.PHONY : src/logic/ServerState.o

# target to build an object file
src/logic/ServerState.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/ServerState.cpp.o
.PHONY : src/logic/ServerState.cpp.o

src/logic/ServerState.i: src/logic/ServerState.cpp.i

.PHONY : src/logic/ServerState.i

# target to preprocess a source file
src/logic/ServerState.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/ServerState.cpp.i
.PHONY : src/logic/ServerState.cpp.i

src/logic/ServerState.s: src/logic/ServerState.cpp.s

.PHONY : src/logic/ServerState.s

# target to generate assembly for a file
src/logic/ServerState.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/logic/ServerState.cpp.s
.PHONY : src/logic/ServerState.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/physics/SQLite.o: src/physics/SQLite.cpp.o

.PHONY : src/physics/SQLite.o

# target to build an object file
src/physics/SQLite.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/physics/SQLite.cpp.o
.PHONY : src/physics/SQLite.cpp.o

src/physics/SQLite.i: src/physics/SQLite.cpp.i

.PHONY : src/physics/SQLite.i

# target to preprocess a source file
src/physics/SQLite.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/physics/SQLite.cpp.i
.PHONY : src/physics/SQLite.cpp.i

src/physics/SQLite.s: src/physics/SQLite.cpp.s

.PHONY : src/physics/SQLite.s

# target to generate assembly for a file
src/physics/SQLite.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/physics/SQLite.cpp.s
.PHONY : src/physics/SQLite.cpp.s

src/physics/physicsFunc.o: src/physics/physicsFunc.cpp.o

.PHONY : src/physics/physicsFunc.o

# target to build an object file
src/physics/physicsFunc.cpp.o:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/physics/physicsFunc.cpp.o
.PHONY : src/physics/physicsFunc.cpp.o

src/physics/physicsFunc.i: src/physics/physicsFunc.cpp.i

.PHONY : src/physics/physicsFunc.i

# target to preprocess a source file
src/physics/physicsFunc.cpp.i:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/physics/physicsFunc.cpp.i
.PHONY : src/physics/physicsFunc.cpp.i

src/physics/physicsFunc.s: src/physics/physicsFunc.cpp.s

.PHONY : src/physics/physicsFunc.s

# target to generate assembly for a file
src/physics/physicsFunc.cpp.s:
	$(MAKE) -f CMakeFiles/NFS_Next_Gen.dir/build.make CMakeFiles/NFS_Next_Gen.dir/src/physics/physicsFunc.cpp.s
.PHONY : src/physics/physicsFunc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... NFS_Next_Gen"
	@echo "... edit_cache"
	@echo "... src/graphics/graphicFunc.o"
	@echo "... src/graphics/graphicFunc.i"
	@echo "... src/graphics/graphicFunc.s"
	@echo "... src/graphics/login.o"
	@echo "... src/graphics/login.i"
	@echo "... src/graphics/login.s"
	@echo "... src/graphics/menu.o"
	@echo "... src/graphics/menu.i"
	@echo "... src/graphics/menu.s"
	@echo "... src/graphics/pauseInTheGame.o"
	@echo "... src/graphics/pauseInTheGame.i"
	@echo "... src/graphics/pauseInTheGame.s"
	@echo "... src/graphics/scoreTable.o"
	@echo "... src/graphics/scoreTable.i"
	@echo "... src/graphics/scoreTable.s"
	@echo "... src/graphics/wrapFunc.o"
	@echo "... src/graphics/wrapFunc.i"
	@echo "... src/graphics/wrapFunc.s"
	@echo "... src/logic/ClientState.o"
	@echo "... src/logic/ClientState.i"
	@echo "... src/logic/ClientState.s"
	@echo "... src/logic/Game.o"
	@echo "... src/logic/Game.i"
	@echo "... src/logic/Game.s"
	@echo "... src/logic/GameState.o"
	@echo "... src/logic/GameState.i"
	@echo "... src/logic/GameState.s"
	@echo "... src/logic/MapGenerator.o"
	@echo "... src/logic/MapGenerator.i"
	@echo "... src/logic/MapGenerator.s"
	@echo "... src/logic/ServerState.o"
	@echo "... src/logic/ServerState.i"
	@echo "... src/logic/ServerState.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/physics/SQLite.o"
	@echo "... src/physics/SQLite.i"
	@echo "... src/physics/SQLite.s"
	@echo "... src/physics/physicsFunc.o"
	@echo "... src/physics/physicsFunc.i"
	@echo "... src/physics/physicsFunc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

